export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
export const BACKEND_ENDPOINT = process.env.REACT_APP_BACKEND_ENDPOINT;

export const HTTP_STATUS_INTERNAL_SERVER = 'INTERNAL_SERVER_ERROR';
export const HTTP_STATUS_CONFLICT = 'CONFLICT';
export const HTTP_STATUS_BAD_REQUEST = 'BAD_REQUEST';
export const HTTP_STATUS_OK = 'OK';
export const HTTP_STATUS_NOT_FOUND = 'NOT_FOUND';
export const HTTP_NO_CONTENT = 'NO_CONTENT';
export const HTTP_UNAUTHORIZED = 'UNAUTHORIZED';
